1. Create 1D,2D,3D array . check it’s shape and dimension.


In [1]:

import numpy as np
import pandas as pd

In [8]:
a=np.array([1,2,3,4])
print(a)
print(a.ndim)
print(a.shape)

[1 2 3 4]
1
(4,)


In [9]:
b=np.array([[1,2,3,4],[5,6,7,8]]) 
print(b)
print(b.ndim)
print(b.shape)

[[1 2 3 4]
 [5 6 7 8]]
2
(2, 4)


In [10]:
c=np.array([[[1,2,3,4],[5,6,7,8]],
            [[9,10,11,12],[13,14,15,16]],
            [[17,18,19,20],[21,22,23,24]]])
print(c)
print(c.ndim)
print(c.shape)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]
3
(3, 2, 4)


2. Create a NumPy array of numbers from 10 to 50 (inclusive) with a step of 5.

In [13]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

3. Generate a 3×3 matrix of random integers between 1 and 20.

In [14]:
np.random.randint(1,20,size=(3,3))

array([[ 8,  3,  8],
       [16, 12,  3],
       [ 6,  9,  9]], dtype=int32)

4. From the array:

   Extract the second row.

   Extract the first column.

   Extract the subarray containing rows 1–2 and columns 2–4.
   
   Replace all even numbers in arr with -1

In [31]:
arr = np.array([[10, 20, 30, 40],
                [50, 60, 70, 80],
                [90, 100, 110, 120]])

print(arr[1])         
print(arr[:, 0])      
print(arr[0:2, 1:4]) 
even_ = arr % 2 == 0
arr[even_] = -1
print(arr) 

[50 60 70 80]
[10 50 90]
[[20 30 40]
 [60 70 80]]
[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]


5. Given:
  
   a = np.array([1, 2, 3])

   b = np.array([4, 5, 6])
   
   Perform element-wise addition, subtraction, multiplication, and division.

In [24]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print("Addition:", np.add(a,b))
print("Subtraction:", np.subtract(a,b))
print("Multiplication:", np.multiply(a,b))
print("Division:", np.divide(a,b))

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


6. Create a 1D array of numbers from 1 to 12. Reshape it into:  3×4 matrix

In [28]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr.reshape(3,4)


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])